# Generated by Django 5.0.6 on 2024-06-07 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fs_metric_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Statement Metric',
                'verbose_name_plural': 'Financial Statement Metrics',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fs_category_created_by', to=settings.AUTH_USER_MODEL)),
                ('metrics', models.ManyToManyField(blank=True, default='', to='finedu_portfolio.financialstatementmetric')),
            ],
            options={
                'verbose_name': 'Financial Statement Category',
                'verbose_name_plural': 'Financial Statement Categories',
            },
        ),
    ]
