# Generated by Django 5.0.6 on 2024-06-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finedu_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatementcategory',
            name='metrics',
        ),
        migrations.AddField(
            model_name='financialstatementmetric',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finedu_portfolio.financialstatementcategory'),
        ),
        migrations.AlterField(
            model_name='financialstatementcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
