# Generated by Django 5.0.6 on 2024-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finedu_portfolio', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'My Portfolio',
                'verbose_name_plural': 'My Portfolios',
            },
        ),
    ]
