# Generated by Django 5.0.6 on 2024-06-19 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finedu_portfolio', '0005_myportfolio_created_at_myportfolio_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholding',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
