# Generated by Django 5.0.6 on 2024-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finedu_portfolio', '0006_companyholding_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyholding',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('£', 'GBP'), ('$C', 'CAD'), ('$AU', 'AUD'), ('kr', 'SEK'), ('¥', 'JPY'), ('₪', 'ILS')]),
        ),
    ]
