# Generated by Django 5.0.6 on 2024-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finedu_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='blog/%Y/%m/'),
        ),
    ]
